# File: azure-pipelines.yaml
# This is the top-level YAML file that will orchestrate the pipeline

trigger: none
#- master

pool:
  vmImage: 'vs2017-win2016'

stages:
- template: pipeline-templates/build.yaml
- template: pipeline-templates/release.yaml
  parameters:
      AdminPassword: $(AdminPassword)
      AdminTestPassword: $(AdminTestPassword)
      HostingPlan: $(HostingPlan)
      ServerName: $(ServerName)
      WebsiteName: $(WebsiteName) 